# Site settings
title: Adam Barton's Flatiron Blog
header-img: img/home-bg.png
email: adam.barton333@gmail.com
copyright_name: adam-barton
description: > # this means to ignore newlines until "baseurl:"
  Adam Barton's Flatiron Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: abarton333
github_username:  adam-barton
learn_profile: adam-barton
email_username: adam.barton333@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
